### ISSUE TITLE
[BUG] Adjusting Decimals Is Just Broken

### ISSUE THREAD

**Issue by Holawenasx2** [eternalUnion/UKPluginConfigurator#1] opened 2023-05-17 00:38 UTC
# Description
So, when you adjust enemies damage or explosion size or all of that, and you have a decimal (like 0.5 or 1.5) if you play after a while or close and reopen Ultrakill the decimal instead of being 0.5 and 1.5, they become 5 and 15.

# Reproduction
It is easy, extremely easy
* Step 1: Edit a value to a decimal (Like Insigna beam to 0.8)
* Step 2: Play a while or reopen Ultrakill, then the value will change to 8

# Console logs
Put any abnormal console log (warnings/error) here. [How to open the console](https://docs.bepinex.dev/articles/user_guide/troubleshooting.html)

# Extras
Extremely annoying when you edit a soldier grenade to 0.75 then when you reopen the game you get a screen nuke

**Comment by eternalUnion** [comment] 2023-05-17 14:32
I could not reproduce this issue fully. The only way to revert a decimal point to an integer, it seems, is to use comma (`0,5`) instead of dot (`0.5`). ~~It does not accept comma~~Commas are not separators (`0,5` is same as `5`), so the value is (internally) reverted to the last valid value (`5` for example) but not visually. Will fix the visual part. If this is not the bug mentioned here, please comment

**Comment by eternalUnion** [comment] 2023-05-17 14:53
Current steps to reproduce the mentioned bug:
* Set a float field to integer `n`
* Edit the field, set field to `n / 10` with a comma separator, press enter / loose focus with mouse / press esc (if `Cancel on ESC` is false)
* Field will remain at `n` since `float.Parse($"{n / 10}")` = n, visual remains the same. Value is internally not changed

**Comment by eternalUnion** [comment] 2023-05-17 15:26
Here is an experimental fix for the issue (in case the bug is what I mentioned above) ~~https://github.com/eternalUnion/UKPluginConfigurator/releases/tag/br1-1.3.1-0~~ (Deleted after fixed)

**Comment by eternalUnion** [comment] 2023-05-19 22:17
Fixed with version 1.3.2

**Closed as completed by eternalUnion** 2023-05-19 22:17 UTC
Labels: bug, released
